### ISSUE TITLE
[Spike] As a user, I want to use multisig for stablecoin management operations, so that the administration of stablecoins is more secure

### ISSUE THREAD

**Issue by AlbertoMolinaIoBuilders** [hashgraph/stablecoin-studio#1000]
### Context

Several Hedera clients have shown interest in using this multi-signature capability.
 
### Description
- multi sig to be made possible for stablecoin management operations (native)
-  Multisig should be at Hedera account level, using keys threshold.
- 
### Open functional/business logic questions
- Should the user select which operations of the stablecoin studio must require multisig? Should that happen during the creation of stablecoin?
  - Or should we support multisig only in a few, predefined operations?
 - Backwards compatibility: What happens to the current stablecoin that was deployed before multisig configuration has been enabled?
- What happens if an operation marked as multisig is later modified?

###Proposed solution
PRD: https://www.notion.so/swirldslabs/Multi-signing-de95b9ddf01f4a5fa37faa191a814a65

**Comment by adovale-IOB** [comment]
Pending validation from Greg
