### ISSUE TITLE
Installation script does not work on Windows machines

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/stablecoin-studio#1003]
**Describe the bug**
Currently our installation script has the following line that use `cp` command which causes a problem on Windows machine as they don't have `cp` command

https://github.com/hashgraph/stablecoin-studio/blob/1a67b7c4d63459ba8825cc89118dd9d1af563684/cli/package.json#L20

**To Reproduce**
Run npm install on Windows

**Expected behavior**
The script should also work on Windows machines

**Comment by MiguelLZPF** [comment]
`fix/1003-windows-cd-bug ` Branch fix this issue
