### ISSUE TITLE
BigDecimal not work with vue reactivity 

### ISSUE THREAD

**Issue by RobinCK** [hashgraph/stablecoin-studio#1048]
**Describe the bug**
cannot refer to #fn

**To Reproduce**
```
const decimal = ref<string>(BigDecimal.fromString('0'));
console.log(decimal.value.toString());
```

**Expected behavior**
toString must be executed

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 120.0.6099.234

**Comment by MiguelLZPF** [comment]
Hello, sorry for the late reply. We don't really understand this issue. Since it's been a while we will close it and if it's still relevant you can reopen it again and add more details. Thank you!
