### ISSUE TITLE
Web Project - "Cannot read properties of undefined" object (in SDK project dependencies)

### ISSUE THREAD

**Issue by woodwardmatt** [hashgraph/stablecoin-studio#1061]
**Describe the bug**
Out of the box (OOTB) local install "Cannot read properties of undefined" object and run the Web UI.

**To Reproduce**

1. Clone the repo
2. Run npm install
3. Configure env files as required
4. Run npm run start in "web" subdirectory
5. (Correct dependency issue as per https://github.com/hashgraph/stablecoin-studio/issues/1060)
6. Observe error message in browser developer console.

**Expected behavior**
Using npm run start successfully runs the Web UI

**Screenshots**
![image](https://github.com/hashgraph/stablecoin-studio/assets/461398/876cffde-8589-4bab-9dd5-f02cbe780968)

**Desktop (please complete the following information):**
- OS: WSL2 (Ubuntu 22.04.3 LTS) under Windows 11 (22631.3155)
- Browser: Brave
- Version: v1.63.165 (Chromium 122.0.6261.94)

**Additional context**
- Fresh clone and install of project.
- Error references: hashgraph/stablecoin-studio/sdk/node_modules/@notabene/pii-sdk/dist/index.js:214

**Comment by RobinCK** [comment]
@AlbertoMolinaIoBuilders this error is not fixed in 1.15.3
![Screenshot 2024-03-12 at 22 34 37](https://github.com/hashgraph/stablecoin-studio/assets/10226014/23524f21-f197-4043-8585-7e186a36785f)

**Comment by AlbertoMolinaIoBuilders** [comment]
@RobinCK , @app-matt , could you try version 1.15.4 and tell me if it works now for you?
