### ISSUE TITLE
Default Testnet Factory Contract Is Not Available

### ISSUE THREAD

**Issue by app-matt** [hashgraph/stablecoin-studio#1066]
**Describe the bug**
The default Testnet factory contract is not available. 

**To Reproduce**
1. Clone the repo
2. Run npm install
3. Configure env files as required
4. Run npm run start in "web" subdirectory
5. Select HashPack wallet
6. Select Testnet and click Accept

**Expected behavior**
No 404 error to be displayed regarding the factory contract.

**Screenshots**
Via Web UI:
<img width="1904" alt="image" src="https://github.com/hashgraph/stablecoin-studio/assets/163220202/b559f7b1-3525-4263-a4f7-94929c8d3c86">

**Desktop (please complete the following information):**
- OS: WSL2 (Ubuntu 22.04.3 LTS) under Windows 11 (22631.3155)
- Browser: Brave
- Version: v1.63.165 (Chromium 122.0.6261.94)

**Additional context**
- The current, unavailable, Testnet factory is listed at: https://github.com/hashgraph/stablecoin-studio/tree/main/cli#factories
- The contract id can be seen as unavailable at: https://hashscan.io/testnet/search-result/0.0.14455068

**Comment by AlbertoMolinaIoBuilders** [comment]
@app-matt the Testnet Factory proxy address we deployed after the testnet reset is : 0.0.2167166. could you set it in your .env and test again (we will update the documentation during the day since we noticed that it is still displaying the old address)

**Comment by AlbertoMolinaIoBuilders** [comment]
@app-matt yes please open a new issue, it's very strange, it should only take the local rpc node if you explicitly set it in your .env file or if you do not configure anything at all (in which case the local rpc is set as the default node). Let's continue the discussion in a new issue.
