### ISSUE TITLE
Hardhat Deployed Factory has no admin address for proxy 

### ISSUE THREAD

**Issue by app-matt** [hashgraph/stablecoin-studio#1067]
**Describe the bug**
When independently deploying a factory contract (i.e. not using the currently unavailable testnet factory contract - see #1066) , the resulting configuration raises an error - "No admin address found for the current factory's proxy"

**To Reproduce**

1. Clone the repo
2. Run npm install
3. Configure env files as required (using the deployed factory address in the web module's .env)
4. Run npm run start in "web" subdirectory
5. Select HashPack wallet
6. Select Testnet and click Accept

**Expected behavior**
No error is shown regarding the deployed factory contract.

**Screenshots**
<img width="1909" alt="image" src="https://github.com/hashgraph/stablecoin-studio/assets/163220202/0f23ead6-cb6e-4e21-beff-d856b7fc7b5d">

**Desktop (please complete the following information):**
- OS: WSL2 (Ubuntu 22.04.3 LTS) under Windows 11 (22631.3155)
- Browser: Brave
- Version: v1.63.165 (Chromium 122.0.6261.94)

**Additional context**
- Approach to deploying the factory contract was as per: https://github.com/hashgraph/stablecoin-studio/tree/main/contracts#deploy-factory

**Comment by AlbertoMolinaIoBuilders** [comment]
@app-matt Could you provide the Factory proxy's address so that we can check it? The proxy admin's address is expected to be included in the proxy's memo, I think it is not clearly indicated in the documentation, we will double check it and update it if required.

**Comment by AlbertoMolinaIoBuilders** [comment]
indeed, your factory's memo field is empty, that is why it is raising the "proxy admin empty" error. 
![image](https://github.com/hashgraph/stablecoin-studio/assets/114951681/53cf46e7-5f3d-4c21-9f38-f0145e0cefcd)

this is the how the "memo" field of our deployed factory proxy looks like:
![image](https://github.com/hashgraph/stablecoin-studio/assets/114951681/8a80912a-e8a2-454e-ba91-81f6219a64cb)

**Comment by pathornteng** [comment]
I can also reproduce this problem. My contract deployed through the script does not have the memo field as well.

**Comment by AlbertoMolinaIoBuilders** [comment]
@pathornteng that's surprising, the code deployed in main seems to work for me : 
![image](https://github.com/hashgraph/stablecoin-studio/assets/114951681/5acf825c-d905-4c4b-a8ae-6ded86b90b78)

the factory proxy has the proxy admin address referenced in its memo
![image](https://github.com/hashgraph/stablecoin-studio/assets/114951681/0125d1c0-5869-438f-b5ff-c6688550a382)

Could you provide more information on how you are deploying the factory? which branch/commit are you using?

**Comment by pathornteng** [comment]
Main branch, fresh clone :)

**Comment by pathornteng** [comment]
<img width="571" alt="image" src="https://github.com/hashgraph/stablecoin-studio/assets/2261017/da1d2086-9f7e-4bf0-9a75-71100f32f325">
Yes it matches yours.

**Comment by AlbertoMolinaIoBuilders** [comment]
@app-matt my bad, I checked the wrong contract :(. So I see that the deployFactory script works as expected since it is properly adding the proxy admin address to the memo field of the factory's proxy.
The .env of the SDK is only used when testing the SDK, so it should have no influence on this.

I am testing the stablecoin locally with your factory proxy and everything seems to work for me.....

![image](https://github.com/hashgraph/stablecoin-studio/assets/114951681/339efda9-7ea7-4422-ade3-f4252161e3d3)

could you maybe remove your local storage and restart eh application "from scratch"?

**Comment by AlbertoMolinaIoBuilders** [comment]
@app-matt we just deployed a new version (commit : 1894b5b6aedc4ee25e3ac08784af358c591ae6d7). Could you try a complete new fresh installation using this commit. I did it, using your .env and everything works, the local rpc is NOT USED.

BEFORE you test, just to be fully aligned, make sure to remove the "local Storage" for "http://localhost:3000"


```
# Log level for the application. The default value is ERROR.
# Acceptable values are ERROR, WARN, INFO, HTTP, VERBOSE, DEBUG and SILLY in order of priority (highest to lowest).
REACT_APP_LOG_LEVEL=ERROR
# JSON array with a factory id in Hedera format `0.0.XXXXX` per environment.
REACT_APP_FACTORIES='[{"Environment":"mainnet","STABLE_COIN_FACTORY_ADDRESS":"0.0.2167166"}, {"Environment":"testnet","STABLE_COIN_FACTORY_ADDRESS":"0.0.3705516"}]'
# The var must be a unique mirror node service for Hedera network, and this is the service which would be used when the UI starts. If the service doesn't require an API key to authorize requests, the API_KEY and HEADER properties must remain empty.
REACT_APP_MIRROR_NODE = '[{"Environment":"mainnet","BASE_URL":"https://mainnet.mirrornode.hedera.com/api/v1/", "API_KEY": "", "HEADER": ""},{"Environment":"testnet","BASE_URL":"https://testnet.mirrornode.hedera.com/api/v1/", "API_KEY": "", "HEADER": ""}]'
REACT_APP_RPC_NODE = '[{"Environment":"mainnet","BASE_URL":"https://mainnet.hashio.io/api/", "API_KEY": "", "HEADER": ""},{"Environment":"testnet","BASE_URL":"https://testnet.hashio.io/api", "API_KEY": "", "HEADER": ""}]'
# This is a proprietary Create React App configuration. You can read more information in its documentation.[Create React App documentation](https://create-react-app.dev/docs/advanced-configuration/)
GENERATE_SOURCEMAP=false
REACT_APP_SHOW_CONFIG=true
```

**Comment by AlbertoMolinaIoBuilders** [comment]
@app-matt indeed that documentation might be confusing since it mentions a Factory's contract ID instead of Factory Proxy's contract ID. However I cannot update that documentation directly, I will contact someone who can. 
On the other hand, the "ENV vars" section of the "README" from the "web" module of the repository was also a bit confusing for the same reason, it will be updated in the next release. 
Thank you for noticing.
