### ISSUE TITLE
Error Creating the stablecoin - For no KYC selected

### ISSUE THREAD

**Issue by app-matt** [hashgraph/stablecoin-studio#1072]
**Describe the bug**
When creating a stablecoin through the Web UI, and specifically selecting not to have KYC enabled, the interface throws an error 

**To Reproduce**

1. Clone the repo
2. Run npm install
3. Configure env files as required
4. Run npm run start in "web" subdirectory
5. Select HashPack wallet
6. Select Testnet and click Accept
7. Create a new stablecoin - specifically select not to have KYC enabled during the process, otherwise use the default control options.
8. Submit the transaction to create the coin, and sign off the transactions in the connected wallet.
9. Observe the error in the Web UI / console (the wallet report successful transactions).
10. The stablecoin is still created (successfully?).

**Expected behavior**
No error is shown upon creating the stablecoin

**Screenshots**
<img width="1910" alt="image" src="https://github.com/hashgraph/stablecoin-studio/assets/163220202/00524af1-ab32-4cf1-9445-06f9de33c387">

**Desktop (please complete the following information):**
- OS: WSL2 (Ubuntu 22.04.3 LTS) under Windows 11 (22631.3155)
- Browser: Brave
- Version: v1.63.165 (Chromium 122.0.6261.94)

**Additional context**
- Error text shown in the console:
```
2024-03-15T01:46:14.183Z - [ERROR]	20006 - The coin 0.0.3711618 does not have KYC active	
StableCoinCreation.tsx:390 Error: The coin 0.0.3711618 does not have KYC active
    at GrantKycCommandHandler.execute (GrantKycCommandHandler.js:66:1)
    at async StableCoinInPort.grantKyc (StableCoin.js:299:1)
    at async LogError.descriptor.value (LogErrorDecorator.js:25:1)
    at async SDKService.grantKyc (SDKService.ts:492:1)
    at async handleFinish (StableCoinCreation.tsx:360:1)
```
- Create Token Transaction List: https://hashscan.io/testnet/transactionsById/0.0.3705474@1710467113.631940469
- Associate Token Transaction: https://hashscan.io/testnet/transactionsById/0.0.3705474@1710467147.425319141

**Comment by AlbertoMolinaIoBuilders** [comment]
@app-matt there is something I do not understand, you said that you used the default options when deploying the new stablecoin except for the "enable KYC account flags", you said that you **disabled** it, but the thing is that by default it is already disabled....
![image](https://github.com/hashgraph/stablecoin-studio/assets/114951681/ff2073d9-ab3e-416e-8f4e-f9df15f6b799)
Did you maybe, enable KYC then disable it before moving to the next step?

**Comment by AlbertoMolinaIoBuilders** [comment]
indeed there is an issue with that, we will fix it and let you know when done.
