### ISSUE TITLE
Stablecoin update operation is not working

### ISSUE THREAD

**Issue by dimasmoliar** [hashgraph/stablecoin-studio#1122]
**Describe the bug**
I have an error INVALID_TREASURY_ACCOUNT_FOR_TOKEN when trying to update the newly created token.

**To Reproduce**
1. Go to https://stablecoinstudio.com
2. Create a new token.
3. Open "Stablecoin details" view.
4. Change token name.
5. Click "Save" button.

**Expected behavior**
Token name should be updated.

**Desktop:**
 - OS: macOS Sonoma 14.3.2
 - Browser: Chrome 124.0.6367.94

**Additional context**
Token: https://hashscan.io/testnet/token/0.0.4350783
Transaction: https://hashscan.io/testnet/transaction/1715604700.363997005

**Comment by AlbertoMolinaIoBuilders** [comment]
@dimasmoliar this looks like a hedera precompiled contract (0x167) issue, I have created an issue on their github repo : https://github.com/hashgraph/hedera-services/issues/13341.

I will keep you posted.
