### ISSUE TITLE
Add complete build option to package.json

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/stablecoin-studio#214]
The current build process requires executing a number of npm commands in a particular sequence, this can be simplified with an additional script in package.json such as

```
    "build": "npm run build:contracts && npm run build:sdk && npm run build:cli && npm run build:web",
```

in the # Building section, add documentation such as

For a first time build, you may build all the modules in one go as follows:

```bash
  npm run build
```

**Comment by AlbertoMolinaIoBuilders** [comment]
the "npm install" command was added to the root "package.json" file.
