### ISSUE TITLE
[CLI][UI] As a User, If I send more than 2^(63)-1 numbers display an info message

### ISSUE THREAD

**Issue by darius279** [hashgraph/stablecoin-studio#280]
### Context

Hedera has a limitation in the maximum number of tokens that the user can mint, send, etc. For that reason, we should avoid different bad behaviour.

https://docs.hedera.com/guides/docs/hedera-api/token-service/tokencreate

### Description

When the user would like to set as initial supply or cash in token, if the number that we send is bigger than 2^(63)-1 we should display a info message to the user saying:
"The number for "field" is bigger than the allowed. Decrease your number and try again please. You could check the limits here: https://docs.hedera.com/guides/docs/hedera-api/token-service/tokencreate"  

### Aceptance criteria

- When I would like to create a token with 18 decimals and I would like to set as initial supply 10000000, an info message is displayed.
- When I've created a token with 18 decimals and I would like to cash in 10000000, an info message is displayed.
- When I would like to create a token with 6 decimals and I try to set as initial supply 10000000, I can create the token.
- When I've created a token with 6 decimals and I would like to cash in 10000000, I successfully cash in those tokens.

**Comment by KennyIoB** [comment]
CLI:
![image](https://github.com/hashgraph/stablecoin-studio/assets/126861852/d791fa28-e78a-4780-b411-984f36ba6607)

**Comment by KennyIoB** [comment]
WEB:
![image](https://github.com/hashgraph/stablecoin-studio/assets/126861852/04b47722-ae26-41ad-bd57-24cae3b519e7)

**Comment by KennyIoB** [comment]
UI
Cash In
![image](https://github.com/hashgraph/stablecoin-studio/assets/126861852/1c467ba4-f810-492a-a1cc-e371798de66d)

**Comment by KennyIoB** [comment]
CLI
Cash In
![image](https://github.com/hashgraph/stablecoin-studio/assets/126861852/9bfa9f2d-451a-4a31-86f6-19392393add2)
