### ISSUE TITLE
[UI] Create and remove custom fees

### ISSUE THREAD

**Issue by darius279** [hashgraph/stablecoin-studio#495]
## Context
Using some services or tools, there are some costs that should be paid. Some places use adverts and  others use some payment systems or are collected by fees. It’s important to give the possibility to the token creators to add, if they want, the possibility to receive some fees when the tokens are transferred from one account to another's.

## Description
Within the operations menu, we should add a new option called: Fees management that it only be visible for users whose FeeScheduleKey matches with its current public key.

_ONLY HTS_

Within this menu will be:
- Add new fee
- Remove fee
- List fees

### Add new fee

First of all, we should check if there ir less than 10 configured fees. If number of fees is 10 we should display the following error:
"You have configured the maximum amount of fees".

When the users selects this option whe should ask the following questions:
- Select the fee type:
  - Fixed fee
  - Fractional fee

#### Fixed fee
- What currency the fee will be paid?
  - HBAR
  - This current token
  - Other token --> If the user selects "Other token" we should ask: "Introduce the other token" and checks if the token exists when it has been introduced. If fails display an error message: "The introduced token does not exists".

- Introduce the fee amount --> Check that the value will be > 0 and < long
- Introduce the account that will receive the fees _(Check what happens if it's necessary to associate the token before and if it's possible to add more than one account. If it's possible, ask the user if they want to add more accounts)_

#### Fractional fee
- Introduce the account that will receive the fees _(Check what happens if it's necessary to associate the token before and if it's possible to add more than one account. If it's possible, ask the user if they want to add more accounts)_
- Introduce the percentage that will be applied, value between 0 and 100. --> _We should internally calculate the denominator and the numerator in order to fit the percentage that the user has been added._
- Introduce the maximum fee to charge (0 means no maximum)
- Introduce the minimum fee to charge (0 means no minimum)
- How will pay the fees, the sender or the receive?
  - Sender (by default)
  - Receiver

### Remove fee

If there is no fees display the following error message: "There is no fees"

When there is at least one fee display the fees lists with the following format:
| Fee type | Currency | Amount or percentage with % | Accounts that will receive the fees | Collector are exempt | FeeAssessmentMethod (Receiver or Sender will pay)

When the user select a fee ask him: "Are you sure you want to delete this fee" Yes | No

### List fees

If there is a fee display the fees list like this:
| Fee type | Currency | Amount or percentage with % | Accounts that will receive the fees | Collector are exempt | FeeAssessmentMethod (Receiver or Sender will pay)

If not display the following message: "There is no fees"

## Acceptance criteria
- When I create an stable coin and keys are managed through the SC, the Fee Schedule key is set to the SmartContract
- I am able to send tokens from an stable coin with fees to another account. (Check via UnitTest using SmartContracts only)
- Given a token and a user whose fee schedule key matches the current user key, I am able to see the "Fees management" section
- Given a token and a user whose fee schedule key matches the current user key, if there is configured 10 keys, when I select "Add custom fee" a warning is displayed
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fixed fee that will be paid with HBARs.
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fixed fee that will be paid with the current token.
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fixed fee that will be paid with other token.
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fractional fee with 0,33% of fee without min or max.
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fractional fee with 5% of fee with 50 HBArs as min without max.
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fractional fee with 5% of fee without min and with 50 HBArs max.
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fractional fee where the payer will be the receiver.
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fractional fee where the payer will be the sender.
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fixed fee where the collector pays fees.
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fixed fee where the collector don't pay fees.
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fractional fee where the collector pays fees.
- Given a token and a user whose fee schedule key matches the current user key, I am able to create a fractional fee where the collector don't pay fees.
- Given a stable coin with custom fees configured, I am able to delete them.
- Given a stable coin with custom fees configured, I am able to configure them.
- Given a stable coin without custom fees, when I click on "Delete" or "List" fees, a warning message is displayed.
- Given a stable coin with custom fees, when I list the stable coin details, I am able to see the fees configuration
- Given a stable coin with custom fees configured, when I have the custom fees available, I am able to modify all of them an only with one transaction all of them are changed.

Subtask
| ID | Status      | Description | Owner  |
|----|-------------|-------------|--------|
| 1  | TODO        | [UI] Create operation button & Add url route & roules files  | 
| 2  | TODO        | [UI]  Create screen | 
| 3  | TODO        | [UI] Test  |

**Comment by mickeymond** [comment]
@darius279 Why am I getting the error below when running the main branch on localhost?

```
Error: Method not implemented.
    at RPCTransactionAdapter.updateCustomFees (TransactionAdapter.js:144:1)
    at UpdateCustomFeesCommandHandler.execute (UpdateCustomFeesCommandHandler.js:79:1)
    at async CustomFeesInPort.updateCustomFees (CustomFees.js:102:1)
    at async LogError.descriptor.value (LogErrorDecorator.js:25:1)
    at async SDKService.updateCustomFees (SDKService.ts:482:1)
    at async handleUpdateTokenFees (index.tsx:415:1)
    at async index.esm.mjs:1936:1
```

**Comment by mickeymond** [comment]
Hey @darius279 ,
Here is my stablecoin id on testnet https://hashscan.io/testnet/token/0.0.5906788
And you are right about the error coming up for **Save changes** button.

**Comment by darius279** [comment]
Hi @mickeymond, could you tell me exactly what values for the custom fees are you trying to set. I would like to reproduce the error.

**Comment by darius279** [comment]
and also, could you tell me what wallet are you using?

**Comment by mickeymond** [comment]
@darius279 Please find the screenshot below for the entries I did.
![image](https://github.com/hashgraph/stablecoin-studio/assets/33749130/213e3891-f97d-45a8-a3eb-818d087b2d7c)

And the Error on the UI below

**Comment by darius279** [comment]
@mickeymond I am able to reproduce your error. We will work on the fix and we will let you know when it will be fixed. The problem only happens with Metamask, if you use Hashpack or Blade will work.

In the meantime, you could add fees using the CLI. I checked and if you add your 0.0.4529985 account should work.

**Comment by mickeymond** [comment]
@darius279 Thanks a lot.
I can also confirm that this is related to Metamask because I connected with Hashpack and it worked.
I also proceeded to use the core Hedera SDK to perform the TokenFeeScheduleUpdateTransaction and it worked well too.
Will be nice to have it working for Metamask as well.

**Comment by mickeymond** [comment]
@darius279 I used the Hedera SDK with my Metamask Private Key to submit the **TokenFeeScheduleUpdateTransaction** transaction which I guess does not go through Stablecoin Smart Contracts => Hedera System Contracts and it worked just fine.
If Metamask can sign and submit transactions directly to the HTS, why the need to do it from a Smart Contract?
I recently used AWS KMS which is ECDSA as a TransactionSigner to interact directly with the HTS so why can't Metamask do the same thing since it is also ECDSA?

**Comment by darius279** [comment]
@mickeymond  If your ECDSA private key through the SDK everything will work fine. For example, using the CLI does no matter if you use a ECDSA or ED25519 keys.

Currently, Metamask only can submit SmartContract transactions. You cannot submit native hedera transaction using Metamask. It hasn’t got integration with HTS.

The problem is that Metamask works through the RPC Relay and the relay is not fully compatible with HTS, for that reason, some operations are not working. 

Our idea is try to have everything working through the SmartContract like cash in, burn, freeze, etc. because if the operations works through SCs we could manage roles per account and also individually per keys.
