### ISSUE TITLE
[Bug][UI] When metamask is locked, if I don't finish the unlock process, the metamask remain blocked

### ISSUE THREAD

**Issue by darius279** [hashgraph/stablecoin-studio#807]
https://github.com/hashgraph/stablecoin-studio/assets/102601367/50f21fd6-71cf-4233-84a6-c60a74ed8247

**Comment by KennyIoB** [comment]
Taking into account all the information in the documentation (listed below) of Metamask and its plugin, when opening the plugin and being in the connection process, there are only two responses, one of error and one of success.
With success is the current behavior of starting the application dashboard
With the error, the change was just added to remove the loading.

While connecting, the loading will be displayed, and if the plugin is closed without finishing connecting (or without giving an error), the loading will remain active, until it connects or fails.

https://docs.metamask.io/wallet/how-to/connect/set-up-sdk/javascript/react/
https://docs.metamask.io/wallet/how-to/connect/access-accounts/
https://github.com/MetaMask/metamask-extension/tree/develop/docs
