### ISSUE TITLE
[UI] Review why we need to ask for the "factory id" when open settings section

### ISSUE THREAD

**Issue by darius279** [hashgraph/stablecoin-studio#886]
### Description
When we open the settings section we are asking for the factory id version and this should be not mandatory. Check and figure out how to fix this situation.

### Acceptance criteria
When the factory id is not set in the .env, the settings section is displayed and fully working.

### Extra
Also fix settings view when coin is not selected

**Comment by martineziob** [comment]
PR -> https://github.com/hashgraph/stablecoin-studio/pull/898
