### ISSUE TITLE
Problem with @hashgraph-dev 1.9.1 version dependencies when installing the tool

### ISSUE THREAD

**Issue by dGarVaqFer** [hashgraph/stablecoin-studio#906]
**Describe the bug**
There is a problem with the private repository that is fetching the dependencies with scope @hashgraph-dev when it installs the SDK module. The installation process is not finding the dependencies in that repository despite running the previous command: 

_npm config set @hashgraph-dev:registry=https://us-npm.pkg.dev/hedera-registry/stablecoin-npm/_

**To Reproduce**
1. Clone the repository and go inside it.
2. Run _npm config set @hashgraph-dev:registry=https://us-npm.pkg.dev/hedera-registry/stablecoin-npm/_ command
3. Run _npm install_

**Expected behavior**
Proper installation of the tool

**Screenshots**
![image](https://github.com/hashgraph/stablecoin-studio/assets/60600562/0da81cfd-8795-4356-abcb-a547cca10082)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Node version: v18.18.0
 - NPM version: 9.8.1

**Additional information**
When I try to install the library manually with the command _npm install @hashgraph-dev/stablecoin-npm-contracts_, it installs the 1.9.0 version of the packages, and not the 1.9.1 that appears in package.json files. So it seems that the 1.9.1 version of this packages has not been deployed to the registry yet.

Thanks!

**Comment by sebastianbugal** [comment]
I am getting the same error when installing but on Mac. Any updates on this?

**Comment by PatoSF** [comment]
Same error on windows, terminal and bash

**Comment by sebastianbugal** [comment]
Any workaround for this?

**Comment by gregscullard** [comment]
I have just pulled the repository into a fresh folder and run `npm install` from the top of the project without issues.

I can't find `npm config set @hashgraph-dev:registry=https://us-npm.pkg.dev/hedera-registry/stablecoin-npm/` in the docs either.

We recently switched NPM repositories so you may have got caught up in between the switch.
