### ISSUE TITLE
[CustodialWallet] Implement the custodial wallet library

### ISSUE THREAD

**Issue by AlbertoMolinaIoBuilders** [hashgraph/stablecoin-studio#985]
Implement the ADR described in : https://www.notion.so/swirldslabs/Custodial-Wallets-library-25670c87033843729271dc499981b83b

**Comment by AlbertoMolinaIoBuilders** [comment]
- Factories implementation : 1 day
- Factories test : 1 day
- Factories documentation : 1 day

- Fireblocks strategy : 3 days
- DFNS strategy : 3 days
- Fireblocks test : 1 days
- DFNS test : 1 days
- Fireblocks documentation : 1 days
- DFNS documentation : 1 days

- module implementation : 1days
- module test : 1days
- module documentation : 1days

- signature implementation : 1days
- signature test : 1days
- signature documentation : 1days

- pipeline : 1day

**Comment by adovale-IOB** [comment]
Pending align name of npm package with Greg
