### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by PatoSF** [hashgraph/stablecoin-studio#996]
**After cloning the repo, I tried installing the packages using npm i but it keeps on giving me this error**
`
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated superagent@7.1.6: Please downgrade to v7.1.5 
if you need IE/ActiveXObject support OR upgrade to v8.0.0 as we no longer support IE and published an incorrect patch version (see https://github.com/visionmedia/superagent/issues/1731)

> hedera-stable-coin@1.11.0 install
> node install.js && npm run build:cli:full && npm run prepare   

Installing dependencies for HASHCONNECT...npm ERR! code E404
npm ERR! 404 Not Found - GET https://us-npm.pkg.dev/hedera-registry/stablecoin-npm/@hashgraph%2fsdk - Requested entity was not found.
npm ERR! 404
npm ERR! 404  '@hashgraph/sdk@2.38.0' is not in this registry.   
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pato SF\AppData\Local\npm-cache\_logs\2023-12-06T18_17_22_381Z-debug-0.log
node:child_process:960
    throw err;
    ^

Error: Command failed: cd C:\Users\Pato SF\Desktop\stablecoin-studio-1/hashconnect/lib && npm install
npm ERR! code E404
npm ERR! 404 Not Found - GET https://us-npm.pkg.dev/hedera-registry/stablecoin-npm/@hashgraph%2fsdk - Requested entity was not found.
npm ERR! 404
npm ERR! 404  '@hashgraph/sdk@2.38.0' is not in this registry.   
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pato SF\AppData\Local\npm-cache\_logs\2023-12-06T18_17_22_381Z-debug-0.log

    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at npmInstall (C:\Users\Pato SF\Desktop\stablecoin-studio-1\install.js:18:3)
    at Object.<anonymous> (C:\Users\Pato SF\Desktop\stablecoin-studio-1\install.js:38:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)    
    at Module._load (node:internal/modules/cjs/loader:958:12)    
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(498) [Uint8Array] [
      110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,      101,  32,  69,  52,  48,  52,  10, 110, 112, 109,  32,  69,       82,  82,  33,  32,  52,  48,  52,  32,  78, 111, 116,  32,       70, 111, 117, 110, 100,  32,  45,  32,  71,  69,  84,  32,      104, 116, 116, 112, 115,  58,  47,  47, 117, 115,  45, 110,      112, 109,  46, 112, 107, 103,  46, 100, 101, 118,  47, 104,      101, 100, 101, 114,  97,  45, 114, 101, 103, 105, 115, 116,      114, 121,  47, 115, 116,  97,  98, 108, 101,  99, 111, 105,      110,  45, 110, 112,
      ... 398 more items
    ]
  ],
  pid: 17064,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(498) [Uint8Array] [
    110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,  
    101,  32,  69,  52,  48,  52,  10, 110, 112, 109,  32,  69,  
     82,  82,  33,  32,  52,  48,  52,  32,  78, 111, 116,  32,  
     70, 111, 117, 110, 100,  32,  45,  32,  71,  69,  84,  32,  
    104, 116, 116, 112, 115,  58,  47,  47, 117, 115,  45, 110,  
    112, 109,  46, 112, 107, 103,  46, 100, 101, 118,  47, 104,  
    101, 100, 101, 114,  97,  45, 114, 101, 103, 105, 115, 116,  
    114, 121,  47, 115, 116,  97,  98, 108, 101,  99, 111, 105,  
    110,  45, 110, 112,
    ... 398 more items
  ]
}

Node.js v18.15.0
npm notice
npm notice New major version of npm available! 9.5.0 -> 10.2.4   
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.4
npm notice Run npm install -g npm@10.2.4 to update!
npm notice
npm ERR! code 1
npm ERR! path C:\Users\Pato SF\Desktop\stablecoin-studio-1
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js && npm run build:cli:full && npm run prepare

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Pato SF\AppData\Local\npm-cache\_logs\2023-12-06T18_13_13_104Z-debug-0.log
`

**Comment by MiguelLZPF** [comment]
Sorry for super-late response 🙏🏽.
Seams an issue with the NPM registry
`npm ERR! 404 Not Found - GET https://us-npm.pkg.dev/hedera-registry/stablecoin-npm/@hashgraph%2fsdk - Requested entity was not found.`
the `hashgraph/sdk` is located here [https://www.npmjs.com/package/@hashgraph/sdk](https://www.npmjs.com/package/@hashgraph/sdk) and you shouldn't have any issues getting it, if so, please open a new issue (or reopen this one) and we will address it. Thanks!
